{
	"version": 1576939719,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/residencias-sheet0.png",
		"images/background.png",
		"images/rua.png",
		"images/lote.png",
		"images/cerca.png",
		"images/playeralma-sheet0.png",
		"images/montanha-sheet0.png",
		"images/montanha-sheet1.png",
		"images/estrelas.png",
		"images/lua-sheet0.png",
		"images/parallax.png",
		"images/parallax2.png",
		"images/presentball-sheet0.png",
		"images/linha-sheet0.png",
		"images/cesta-sheet0.png",
		"images/cestaponto-sheet0.png",
		"images/dinamictext.png",
		"images/effect-sheet0.png",
		"images/effect-sheet1.png",
		"images/statictext.png",
		"images/doende-sheet0.png",
		"images/doende-sheet1.png",
		"images/iluminacao-sheet0.png",
		"images/bonus-sheet0.png",
		"images/bonus-sheet1.png",
		"images/seta-sheet0.png",
		"images/bgbonus-sheet0.png",
		"images/spritestutorial-sheet0.png",
		"images/spritestutorial-sheet1.png",
		"images/spritestutorial-sheet2.png",
		"images/controle-sheet0.png",
		"images/controle-sheet1.png",
		"images/botao-sheet0.png",
		"images/bg-sheet0.png",
		"images/menubtn-sheet0.png",
		"images/menubtn-sheet1.png",
		"images/menubtn-sheet2.png",
		"images/setarola-sheet0.png",
		"images/menubg-sheet0.png",
		"images/recordtag-sheet0.png",
		"images/titulo-sheet0.png",
		"images/fumaca.png",
		"images/fire-sheet0.png",
		"images/fire-sheet1.png",
		"images/fogo.png",
		"media/bola bateu metal.m4a",
		"media/bola bateu metal.ogg",
		"media/bola errou 2.m4a",
		"media/bola errou 2.ogg",
		"media/bola errou.m4a",
		"media/bola errou.ogg",
		"media/bola kick 2.m4a",
		"media/bola kick 2.ogg",
		"media/bola kick.m4a",
		"media/bola kick.ogg",
		"media/pegou 1.m4a",
		"media/pegou 1.ogg",
		"media/pegou 2.m4a",
		"media/pegou 2.ogg",
		"media/pegou 3.m4a",
		"media/pegou 3.ogg",
		"media/pegou 4.m4a",
		"media/pegou 4.ogg",
		"media/balloon pop.m4a",
		"media/balloon pop.ogg",
		"media/clap 1.m4a",
		"media/clap 1.ogg",
		"media/clap 2.m4a",
		"media/clap 2.ogg",
		"media/clap 3.m4a",
		"media/clap 3.ogg",
		"media/clap 4.m4a",
		"media/clap 4.ogg",
		"media/acertou1.m4a",
		"media/acertou1.ogg",
		"media/acertou2.m4a",
		"media/acertou2.ogg",
		"media/acertou3.m4a",
		"media/acertou3.ogg",
		"media/aceleracao constante.m4a",
		"media/aceleracao constante.ogg",
		"media/acelerando.m4a",
		"media/acelerando.ogg",
		"media/freio motor.m4a",
		"media/freio motor.ogg",
		"media/motor ligado.m4a",
		"media/motor ligado.ogg",
		"media/pe na embreagem.m4a",
		"media/pe na embreagem.ogg",
		"media/primeiramarcha.m4a",
		"media/primeiramarcha.ogg",
		"media/bateu 1.m4a",
		"media/bateu 1.ogg",
		"media/bateu 2.m4a",
		"media/bateu 2.ogg",
		"media/turbo.m4a",
		"media/turbo.ogg",
		"media/turbo2.m4a",
		"media/turbo2.ogg",
		"media/musica.m4a",
		"media/musica.ogg",
		"media/sino start.m4a",
		"media/sino start.ogg",
		"media/countdown1.m4a",
		"media/countdown1.ogg",
		"media/countdown2.m4a",
		"media/countdown2.ogg",
		"media/tema natalino.m4a",
		"media/tema natalino.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}